// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgK0-4I1-Tc-r51Dz_MInwBGR9ZbEYYJ0',
    appId: '1:563910306319:web:0672f8b978d42b53e6517a',
    messagingSenderId: '563910306319',
    projectId: 'nitimitra-94986',
    authDomain: 'nitimitra-94986.firebaseapp.com',
    storageBucket: 'nitimitra-94986.firebasestorage.app',
    measurementId: 'G-V0H7NMBS00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDodw4XlMcWAy8gmjtT6KkzTVwxTCTAsgA',
    appId: '1:563910306319:android:3800781504503f2fe6517a',
    messagingSenderId: '563910306319',
    projectId: 'nitimitra-94986',
    storageBucket: 'nitimitra-94986.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjYvvKOecJPSUbCHueY_9S56eUhZMiPJ0',
    appId: '1:563910306319:ios:74733e4ff7fda5f7e6517a',
    messagingSenderId: '563910306319',
    projectId: 'nitimitra-94986',
    storageBucket: 'nitimitra-94986.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjYvvKOecJPSUbCHueY_9S56eUhZMiPJ0',
    appId: '1:563910306319:ios:74733e4ff7fda5f7e6517a',
    messagingSenderId: '563910306319',
    projectId: 'nitimitra-94986',
    storageBucket: 'nitimitra-94986.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgK0-4I1-Tc-r51Dz_MInwBGR9ZbEYYJ0',
    appId: '1:563910306319:web:bc01b8de8fec36e4e6517a',
    messagingSenderId: '563910306319',
    projectId: 'nitimitra-94986',
    authDomain: 'nitimitra-94986.firebaseapp.com',
    storageBucket: 'nitimitra-94986.firebasestorage.app',
    measurementId: 'G-49JFHQTKZ7',
  );

}